version: '3'

services:
  app:
    image: 644435390668.dkr.ecr.eu-west-2.amazonaws.com/yotamh_repo:latest
    depends_on:
      - mem
  
  mem:
    image: memcached:1.6.18
  
  nginx:
    image: nginx:1.23.3
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./target/classes/static:/usr/share/nginx/html
    depends_on:
      - app